# Generated by Django 4.0.6 on 2022-07-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liquid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('score', models.SmallIntegerField()),
                ('volume', models.FloatField()),
                ('strength', models.FloatField()),
                ('description', models.TextField()),
                ('is_produced', models.BooleanField(default=True)),
            ],
        ),
    ]
